
server:
  port: ${PORT:8888}

#logging:
#  level:
#    ROOT: DEBUG
#    io.github.jhipster: DEBUG
#    com.mycompany.myapp: DEBUG
application:
  client-app:
    name: "@project.name@"
  auth:
    realm: music
    server: ${AUTH_SERVER:http://localhost:9080}
    cluster-server: ${CLUSTER_AUTH_SERVER:http://localhost:9080}
    audience: "myaudience"
    provider-id: songfind # Has to match spring.security.oauth2.client.registration.{provider-id}

spring:
  security:
    oauth2:
      client:
        registration:

          songfind: # this is the provider_id -> has to match ${application.auth.provider-id} value
            client-id: ${AUTH_CLIENT_ID:@songfind.client.id@}
            client-secret: ${AUTH_CLIENT_SECRET:@songfind.client.secret@}
            scope: openid, spring-front, email, profile
            authorization-grant-type: authorization_code # this could also be password or something else <-- Review/Check

          spotify:
            client-id: ${AUTH_SPOTIFY_CLIENT_ID:@spotify.client.id@}
            client-secret: ${AUT_SPOTIFY_CLIENT_SECRET:@spotify.client.secret@}
            authorization-grant-type: authorization_code
            authentication-scheme: query
            client-authentication-scheme: form
            scope: user-read-private, user-read-email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

        provider:
          songfind:
            authorization-uri: ${application.auth.server}/auth/realms/${application.auth.realm}/protocol/openid-connect/auth
            jwk-set-uri: ${application.auth.cluster-server}/auth/realms/${application.auth.realm}/protocol/openid-connect/certs
            token-uri: ${application.auth.cluster-server}/auth/realms/${application.auth.realm}/protocol/openid-connect/token
            issuer-uri: ${application.auth.cluster-server}/auth/realms/${application.auth.realm}
          spotify:
            token-uri: https://accounts.spotify.com/api/token
            authorization-uri: https://accounts.spotify.com/authorize
            user-name-attribute: display_name
            user-info-uri: https://api.spotify.com/v1/me


management:
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true




